#!/bin/bash
# PART 1  
# [SOURCE] SLR350Ni user manual (see "https://github.com/yanniedog/AIS/blob/main/slr350ni.pdf")
# Checking if backup directory exists, then creating a backup of config.txt
sudo [ ! -d /boot/backup ] && sudo mkdir /boot/backup
sudo cp /boot/config.txt /boot/backup/$(date +"%FT%H%M%S")-config.txt
sudo sh -c "echo ' ' >> /boot/config.txt"
sudo sh -c "echo '# Appended by SLR350Ni_setup script by Yanniedog. Source: https://github.com/yanniedog/AIS/blob/main/SLR350Ni_setup' >> /boot/config.txt"
sudo sh -c "echo '# Enable UART (enable ttys0) for the AIS receiver' >> /boot/config.txt"
sudo sh -c "echo 'enable_uart=1' >> /boot/config.txt"
echo ---------------
echo 'Please reboot, then run SLR350Ni_setup_part2'
echo ---------------
